export const lastPlayedSong = "lastPlayedSong"
export const isPermission = "audioPermissionGranted"
export const FavouritSong = "FavouritSong"
export const PlayListSong = "PlayListSong"
export const PlayHistory = "PlayHistory"